# Generated by Django 4.2.5 on 2023-09-24 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Task Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[{'Pending', 'pending'}, {'completed', 'Completed'}], default='pending', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
